[WIP]コントローラーのテスト
Koh0214/chat-space1 pull request #16
Opened 2017-01-17 07:55 UTC by Koh0214

2017-01-19 11:26 UTC, Koh0214 commented
Messageモデルのテスト結果
![2017-01-19 20 25 07](https://cloud.githubusercontent.com/assets/22772196/22105052/8fc00d92-de85-11e6-9eb5-664c96018898.png)

2017-01-19 11:32 UTC, Koh0214 commented
messageモデルのテストを実装したのですが、
テスト内容が漏れていないかの確認をお願いします！

2017-01-19 11:41 UTC, KoichiOzaki commented on spec/models/message_spec.rb
> +    it "is valid with a body, user_id, group_id" do
specを書く際は英語がうまくつがるように書くと良いです。
このまでは実行時に
Message
valid
is valid with a body, user_id, group_id
みたいになってしまうので少し違和感があります。
contextを使うときにはwhen xxxxみたいに書いてあげるとうまく英語がつながります。

2017-01-19 11:43 UTC, KoichiOzaki commented
messageテストの内容としては良いです！
一点気になった所をコメントしたのでそこだけ直して、引き続き進めていきましょう＼(^o^)／

2017-01-21 08:03 UTC, Koh0214 commented
![2017-01-20 19 21 24](https://cloud.githubusercontent.com/assets/22772196/22173082/754d2338-dffb-11e6-9563-de705d65a2d6.png)
![2017-01-21 17 00 16](https://cloud.githubusercontent.com/assets/22772196/22173083/756ecd1c-dffb-11e6-88ce-6486e094650a.png)
![2017-01-21 17 00 26](https://cloud.githubusercontent.com/assets/22772196/22173084/758986e8-dffb-11e6-891e-9d6af381ae3e.png)

2017-01-21 08:46 UTC, Koh0214 commented
![2017-01-21 17 45 09](https://cloud.githubusercontent.com/assets/22772196/22173289/851883f6-e001-11e6-8daa-a427b6458228.png)

2017-01-21 11:48 UTC, Koh0214 commented
コントローラーのテストの結果
![2017-01-21 20 44 17](https://cloud.githubusercontent.com/assets/22772196/22174169/f4c14706-e01a-11e6-98e9-df4d3928a833.png)

2017-01-21 12:57 UTC, caminogr requested changes
いくつかコメント致しました
ご確認下さい！

2017-01-21 12:57 UTC, kaminora commented on spec/models/message_spec.rb
> +  context "is valid" do
contextの書き方はこの記事とか参考にしてみて下さい
http://kei-p3.hatenablog.com/entry/2016/05/25/235124

なんとなくでメソッドを利用するのではなく、実際にどういう使われ方をしているか調べてから利用する癖をつけてください！！

2017-01-21 12:57 UTC, kaminora commented on spec/models/message_spec.rb
> +    it "with a body, user_id, group_id" do
ここは変更する必要はないと思います！

2017-01-21 12:57 UTC, kaminora commented on spec/models/message_spec.rb
> +    it "without body" do
ここも文として少しおかしいですね！

2017-01-21 12:57 UTC, kaminora commented on spec/models/group_spec.rb
> +    updated_at { Faker::Time.between(2.days.ago, Date.today, :all) }
これだとcreated_atが今日なのにupdated_atが２日前っていう状況がうまれませんか？

2017-01-21 12:57 UTC, kaminora commented on spec/controllers/messages_contoller_spec.rb
> +      binding.pry
binding.pryは絶対にコミットしないようにしましょう！

2017-01-21 12:57 UTC, kaminora commented on spec/models/group_spec.rb
> -end
このファイルを削除したのはなぜでしょうか？

2017-01-21 12:57 UTC, kaminora commented on spec/controllers/messages_contoller_spec.rb
> +    let(:user) { FactoryGirl.create(:user) }
`FactoryGirl`を書かないでuserを作成しましょう！
できない場合は書かなくてもuserを作成できるように設定しましょう

2017-01-21 12:57 UTC, kaminora commented on spec/factories/users.rb
> +  end
groupについてのfactoryはファイルを分けて定義して下さい！
userのfactoryの中でgroupについてのfactoryを呼び出すようにすればできるはずです

2017-01-21 12:57 UTC, kaminora commented on spec/factories/users.rb
>    end
こちらもそれ用にファイルを用意しましょう

2017-01-21 12:57 UTC, kaminora commented on spec/controllers/messages_contoller_spec.rb
> +    let(:message) { FactoryGirl.create(:message) }
userと同じく`FactoryGirl`を書かずにmessageを生成しましょう

2017-01-21 12:57 UTC, kaminora commented on spec/controllers/messages_contoller_spec.rb
> +      binding.pry
binding.pry残ってます

2017-01-21 12:57 UTC, kaminora commented on spec/factories/users.rb
>  	pass = Faker::Internet.password(8)
インデントがおかしいですね！

2017-01-21 12:57 UTC, kaminora commented on spec/factories/users.rb
> +    name
fakerを使うのをやめたのはなぜでしょうか？

2017-01-21 12:57 UTC, kaminora commented on spec/controllers/messages_contoller_spec.rb
> +      group = user.groups.first
せっかくfactoryで create(:group) を使えるように定義してるので使って頂きたいです..!!!

2017-01-21 13:07 UTC, Koh0214 commented on spec/controllers/messages_contoller_spec.rb
> +      binding.pry
最終的に削除すればいいのかと勘違いしていました！
これからコミットしないように気をつけます！

ありがとうございます！

2017-01-21 13:07 UTC, Koh0214 commented on spec/controllers/messages_contoller_spec.rb
> +      binding.pry
最終的に削除すればいいのかと勘違いしていました！
これからコミットしないように気をつけます！

ありがとうございます！

2017-01-21 13:09 UTC, Koh0214 commented on spec/factories/users.rb
>  	pass = Faker::Internet.password(8)
すみません！
修正しました！

もう無いようにします！

2017-01-21 13:13 UTC, Koh0214 commented on spec/models/group_spec.rb
> -end
group.rb, group_user.rb, message.rb, をそれぞれ個別ファイルに分けました！

どうファイル内に必要と勘違いしていました！

2017-01-21 13:15 UTC, Koh0214 commented on spec/factories/users.rb
> +  end
個別ファイルに分けました！

2017-01-21 13:15 UTC, Koh0214 commented on spec/factories/users.rb
>    end
こちらも個別ファイルに分けました！

2017-01-21 13:15 UTC, Koh0214 commented on spec/factories/users.rb
>    end
こちらも個別ファイルに分けました！

2017-01-21 13:19 UTC, Koh0214 commented on spec/controllers/messages_contoller_spec.rb
> +    let(:user) { FactoryGirl.create(:user) }
削除しました！！

2017-01-21 13:19 UTC, Koh0214 commented on spec/controllers/messages_contoller_spec.rb
> +    let(:message) { FactoryGirl.create(:message) }
削除しました！！

2017-01-21 13:21 UTC, Koh0214 commented on spec/factories/users.rb
> +    name
復活させました！

エラー原因を探ってあちこち弄っていた時に消したままでした。
ご指摘ありがとうございます！

2017-01-21 13:32 UTC, Koh0214 commented on spec/models/group_spec.rb
> +    updated_at { Faker::Time.between(2.days.ago, Date.today, :all) }
た、たしかに、、、、

すみません。修正しました！

2017-01-21 14:19 UTC, Koh0214 commented on spec/models/message_spec.rb
> +  context "is valid" do
アドバイスありがとうございます！

数サイトの記事を読んで修正しました！

2017-01-21 14:20 UTC, Koh0214 commented on spec/models/message_spec.rb
> +    it "with a body, user_id, group_id" do
修正しました！

2017-01-21 14:20 UTC, Koh0214 commented on spec/models/message_spec.rb
> +    it "without body" do
修正しました！

2017-01-21 14:20 UTC, Koh0214 commented
context修正後のテスト結果
![2017-01-21 23 18 54](https://cloud.githubusercontent.com/assets/22772196/22175018/2f682d92-e030-11e6-9a43-0df586dd521c.png)

2017-01-21 14:32 UTC, Koh0214 commented on spec/controllers/messages_contoller_spec.rb
> +      group = user.groups.first
user - group_user - user
というアソシエーションのために、
user.rbの中で使用しているのですが、どうでしょうか・・？

多対多のアソシエーションをもっともスマートに組める方法かなと思ったのですが。。。

2017-01-22 06:20 UTC, merged