[WIP]deviseの導入とモデル、コントローラーの作成
Koh0214/chat-space1 pull request #5
Opened 2017-01-07 11:43 UTC by Koh0214

#WHAT
deviseの導入
モデルの作成
コントローラーの作成

#WHY
ユーザー管理のため

2017-01-07 12:04 UTC, Koh0214 commented
bundel install, rails g devise:viewsしたものと、
クローンしたビューファイルの中身を入れ替えました。

edit.html.erbが２つあり、記述をみて判断しました。

ご確認いただけると助かります。

2017-01-08 04:36 UTC, DaikiInaba commented
ファイルの置き換えは問題ございませんが、erbファイルが残っているのでこちらもhamlに変換しましょう！

2017-01-09 02:08 UTC, caminogr requested changes

2017-01-09 02:08 UTC, kaminora commented on app/assets/stylesheets/user.scss
> +    }
&が使えてていい感じですね！
このclearfixのプロパティはこれからもよく使う事が予想されるのでmixinで定義したほうがよさそうです！
カリキュラムにも書いてあると思うので確認してみてください！

2017-01-09 02:22 UTC, Koh0214 commented on app/assets/stylesheets/user.scss
> +    }
ファイルの一番上にmixinでclearfixを定義しました！

2017-01-09 02:27 UTC, kaminora commented on app/assets/stylesheets/user.scss
> +
こちらはmixinディレクトリをつくってその中に別のファイルとして定義してあげましょう！

2017-01-09 02:31 UTC, kaminora commented
LGTMです！
お疲れさまです！
次に進んでください！！！

2017-01-09 02:32 UTC, merged